// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzznpmnerwqukewzisit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6em5wbW5lcndxdWtld3ppc2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTgzMjAsImV4cCI6MjA3MTc3NDMyMH0.uIoT4YCnQ07FIwnzAa0t1foCMagr98A06llq1h11qVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});